/**
 * Static Site Content Pipeline
 * Parses all physical markdown files in /content/posts/
 * and generates statically compiled assets for build and preview.
 */

import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

const POSTS_DIR = path.resolve(process.cwd(), 'content/posts');
const OUTPUT_JSON = path.resolve(process.cwd(), 'src/data/generatedPosts.json');
const OUTPUT_TS = path.resolve(process.cwd(), 'src/data/generatedPosts.ts');

export interface ParsedMarkdownPost {
  id: string;
  title: string;
  slug: string;
  date?: string;
  updated?: string;
  readingTime?: string;
  hardware?: string;
  status: 'draft' | 'published';
  category: 'mac' | 'iphone' | 'hybrid' | 'benchmarks';
  hardwareArch: 'apple-m' | 'iphone-a' | 'npu' | 'hybrid';
  hardwareLabel: string;
  tags: string[];
  primaryTag?: string;
  coverImage?: string;
  metrics: {
    primaryValue: string;
    primaryLabel: string;
    secondaryValue: string;
    secondaryLabel: string;
  };
  markdown: string;
  updatedAt: string;
  wordCount: number;
  readTime: string;
  filePath: string;
}

export async function compileStaticContent(): Promise<ParsedMarkdownPost[]> {
  console.log('\n[Static Site Pipeline] Starting markdown compilation from /content/posts/...');

  if (!fs.existsSync(POSTS_DIR)) {
    fs.mkdirSync(POSTS_DIR, { recursive: true });
    console.log(`[Static Site Pipeline] Created missing posts directory: ${POSTS_DIR}`);
  }

  const files = await fs.promises.readdir(POSTS_DIR);
  const mdFiles = files.filter((f) => f.endsWith('.md'));

  const parsedPosts: ParsedMarkdownPost[] = [];

  for (const file of mdFiles) {
    const fullPath = path.join(POSTS_DIR, file);
    try {
      const rawContent = await fs.promises.readFile(fullPath, 'utf-8');
      const { data, content } = matter(rawContent);

      const words = content.trim().split(/\s+/).filter(Boolean).length;
      const readMinutes = Math.max(1, Math.ceil(words / 200));

      const isEnglish = file.endsWith('.en.md');
      const baseSlug = file.replace(/\.en\.md$/, '').replace(/\.md$/, '');

      const post: ParsedMarkdownPost = {
        id: data.id || (isEnglish ? `${baseSlug}-en` : baseSlug),
        title: data.title || baseSlug.replace(/-/g, ' '),
        slug: data.slug || baseSlug,
        date: data.date || (data.updatedAt ? data.updatedAt.slice(0, 10) : new Date().toISOString().slice(0, 10)),
        readingTime: data.readingTime || data.readTime || `${readMinutes} min`,
        hardware: data.hardware ? (Array.isArray(data.hardware) ? data.hardware.join(' • ') : data.hardware) : (data.hardwareLabel || 'Apple Silicon'),
        updated: data.updated || undefined,
        status: data.status === 'published' ? 'published' : 'draft',
        category: data.category || 'mac',
        hardwareArch: data.hardwareArch || 'apple-m',
        hardwareLabel: data.hardwareLabel || 'Apple Silicon',
        tags: Array.isArray(data.tags) ? data.tags : ['Apple Silicon'],
        primaryTag: data.primaryTag || (Array.isArray(data.tags) && data.tags[0]) || undefined,
        coverImage: data.coverImage || '',
        metrics: {
          primaryValue: data.metrics?.primaryValue || '45 tok/s',
          primaryLabel: data.metrics?.primaryLabel || (isEnglish ? 'Inference Speed' : 'Inferenshastighed'),
          secondaryValue: data.metrics?.secondaryValue || '32 GB',
          secondaryLabel: data.metrics?.secondaryLabel || (isEnglish ? 'RAM Allocation' : 'RAM Allokering'),
        },
        markdown: content.trim(),
        updatedAt: data.updatedAt || new Date().toISOString(),
        wordCount: data.wordCount || words,
        readTime: data.readTime || `${readMinutes} min`,
        filePath: `content/posts/${file}`,
      };

      parsedPosts.push(post);
      console.log(
        `  ✓ ${file} [${post.status.toUpperCase()}] · ${post.wordCount} ord · ${post.hardwareLabel}`
      );
    } catch (err: any) {
      console.error(`  ✕ Fejl ved parsing af ${file}:`, err.message);
    }
  }

  // Sort: published first, then by date descending
  parsedPosts.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime());

  // Ensure src/data directory exists
  const dataDir = path.dirname(OUTPUT_JSON);
  if (!fs.existsSync(dataDir)) {
    fs.mkdirSync(dataDir, { recursive: true });
  }

  // Write JSON
  await fs.promises.writeFile(OUTPUT_JSON, JSON.stringify(parsedPosts, null, 2), 'utf-8');

  // Write TypeScript wrapper
  const tsContent = `// Automatically generated by scripts/build-static-content.ts
// Do not edit manually. Edit files in /content/posts/ instead.

import postsData from './generatedPosts.json';
import { StoredPost } from './adminSeed';

export const staticMarkdownPosts: StoredPost[] = postsData as StoredPost[];

export default staticMarkdownPosts;
`;
  await fs.promises.writeFile(OUTPUT_TS, tsContent, 'utf-8');

  console.log(
    `[Static Site Pipeline] Successfully compiled ${parsedPosts.length} posts to ${path.relative(process.cwd(), OUTPUT_JSON)}`
  );

  return parsedPosts;
}

// Direct execution via CLI
if (process.argv[1] && process.argv[1].endsWith('build-static-content.ts')) {
  compileStaticContent()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('[Static Site Pipeline] Build failed:', err);
      process.exit(1);
    });
}
