// Automatically generated by scripts/build-static-content.ts
// Do not edit manually. Edit files in /content/posts/ instead.

import postsData from './generatedPosts.json';
import { StoredPost } from './adminSeed';

export const staticMarkdownPosts: StoredPost[] = postsData as StoredPost[];

export default staticMarkdownPosts;
